### PR TITLE
Use mpint representation for shared_secret when deriving keys in pure-PQ key exchange, and some other bug fixes; fixes #119

### LINKED ISSUE #119: v8 branch pure-PQ KEMs do not use mpint representation for shared_secret in SSH KDF
When deriving the various keys in `kex_derive_keys`, the pure-PQ functions that handle encrypting and decrypting the shared secret, `kex_kem_generic_enc` and `kex_kem_generic_dec`, write only the shared secret data itself into the buffer that is later input to the KDF. They call `sshbuf_reserve` and pass a pointer directly into the buffer contents to `OQS_KEM_encaps` or `_decaps`. The SSH spec requires the shared secret input to the KDF to be in the mpint format, which has 4 bytes of length prepended to it. This causes the keys to be derived in a manner not compliant with the spec. In `kex_derive_keys`, `shared_secret` ends up being 16 bytes, for example, when it should be 20 (4 bytes length + 16 bytes secret).

The relevant code is at https://github.com/open-quantum-safe/openssh/blob/0c5eac6a3ba249f73bb953745cf109bdf281eafd/kexoqs.c#L91-L98 for encrypting, and https://github.com/open-quantum-safe/openssh/blob/0c5eac6a3ba249f73bb953745cf109bdf281eafd/kexoqs.c#L130-L135 for decrypting.

The v7.9 branch had this correct, and there's even a note calling it out at https://github.com/open-quantum-safe/openssh/blob/f41bbe652c522db1bec388f82db369e4e5f0f405/kexpqoqsc.c#L297-L310 and https://github.com/open-quantum-safe/openssh/blob/f41bbe652c522db1bec388f82db369e4e5f0f405/kexpqoqss.c#L282-L295. The shared secret data there is written into the buffer as an ssh_string, which prepends the same 4 bytes of length that makes it conform to the mpint format.

As an aside, I believe the hybrid case is correct, but I haven't been able to test it yet. `kex_kem_generic_with_ec_enc` and `kex_kem_generic_with_ec_dec` both write the shared secret to the relevant buffer with `sshbuf_put_string`, in the same way the v7.9 code does, and so the prepended length should be present. See https://github.com/open-quantum-safe/openssh/blob/0c5eac6a3ba249f73bb953745cf109bdf281eafd/kexoqsecdh.c#L337-L343 and https://github.com/open-quantum-safe/openssh/blob/0c5eac6a3ba249f73bb953745cf109bdf281eafd/kexoqsecdh.c#L262-L272.

### PR DESCRIPTION
**Pull request by kevinmkane**
Other bug fixes:

1. Increase MAX_PROP to 160. Large numbers of proposals due to all the OQS algorithms can cause a non-spec-compliant selection of algorithm if this value is too low and client and server order their proposals differently. This had been fixed in v7 by #85 but returned in the v8 branch.
2. When calling `ssh-keygen` with the `-t` parameter to specify the key type for one of the ECDSA hybrids, but using the short name instead of the full `ssh-ecdsa-xxxxxxx` name, ECDSA keys would always be generated on P-256. Instead, always use the specified curve.
3. `kex_kem_generic_{enc,dec}` could use an uninitialized variable as the return value if the call to the underlying liboqs function failed. On the small chance that variable happened to have a zero in it, this would look like a successful result to teh caller. Return `SSH_ERR_LIBCRYPTO_ERROR` in these cases instead.

### CODE REVIEW

File: kexoqs.c [hunk 1]
```diff
@@ -127,15 +136,24 @@ static int kex_kem_generic_dec(OQS_KEM *kem,
...
+  if ((kem_key = malloc(kem->length_shared_secret)) == NULL) {
+    r = SSH_ERR_ALLOC_FAIL;
     goto out;
+  }
   if (OQS_KEM_decaps(kem, kem_key, ciphertext, kex->oqs_client_key) != OQS_SUCCESS) {
+    r = SSH_ERR_LIBCRYPTO_ERROR;
     goto out;
   }
+  if ((r = sshbuf_put_string(buf, kem_key, kem->length_shared_secret)) != 0)
+    goto out;
```
Comment (dstebila) [inline kexoqs.c]:
```suggestion
  if ((r = sshbuf_put_string(buf, kem_key, kem->length_shared_secret)) != 0) {
    goto out;
  }
```

**Review by dstebila — APPROVED** [review]

File: kexoqs.c (hunk 1 above)
Comment (kevinmkane) [reply kexoqs.c]: I'm fine either way. I went without the braces here because the one-line body if at line 93 also omits them, and I was trying to be consistent with existing style.

Comment (dstebila) [reply kexoqs.c]: I don't like that style because it leads to bugs, e.g. Apple's [goto fail bug](https://www.imperialviolet.org/2014/02/22/applebug.html).  I wouldn't go so far as to change all occurrences within the OpenSSH code, but in code we add, I'd prefer to include it.

Comment (kevinmkane) [reply kexoqs.c]: Fine by me. I prefer that style too, but as I said, the existing code had it the other way. I'll add another commit with this change.

**Comment by kevinmkane** [comment]
> 3\. `kex_kem_generic_{enc,dec}` could use an uninitialized variable as the return value if the call to the underlying liboqs function failed. On the small chance that variable happened to have a zero in it, this would look like a successful result to teh caller. Return `SSH_ERR_LIBCRYPTO_ERROR` in these cases instead.

Actually I'm wrong about this: it's worse. The `r` variable will be initialized, but to zero based on previous calls succeeding that assign to it. So it's certain failures in the calls into liboqs won't get caught. The fix is still correct, fortunately.

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Thanks @kevinmkane!
